version: '1.0'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn backend.api.main:app --host localhost --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - pip_cache:/tmp/pip-cache
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: streamlit run frontend/app.py --server.port=8501 --server.address=localhost
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - pip_cache:/tmp/pip-cache
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pip_cache:
