services:
  backend:
    image: terradata-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  frontend:
    image: terradata-app:latest
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app/frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
