version: '3.8'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app/backend/api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: .
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app/frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1 