version: '1.0'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - pip_cache:/tmp/pip-cache
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pip_cache:
